name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: login the Docker
      env:
        DOCKER_LOGIN: ${{secrets.DOCKER_LOGIN}}
        DOCKER_PASSWORD: ${{secrets.DOCKER_PASSWORD}}
      run: docker login -u $DOCKER_LOGIN -p $DOCKER_PASSWORD
    - name: Build the Docker image
      run: docker-compose build
    - name: Push to Dockerhub
      run: docker push camilovelasquez/backend:latest
