name: Docker Image CI

on:
  push:
    branches: [ "main" ]
  pull_request:
    branches: [ "main" ]

jobs:

  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v4
    - name: Set up JDK 11
      uses: actions/setup-java@v3
      with:
        java-version: '11'
    - name: Build java
      run: |
        cd Backend\springboot-postgresql-docker-compose-master
        ./mvnw clean package -DskipTests
    - name: Build the Docker image
      run: docker-compose up --build. --file Dockerfile --tag my-image-name:$(date +%s)
